name: Monthly Workflow

on:
  schedule:
    # Runs at 00:00 UTC on days 28 through 31 of every month 
    - cron: '0 0 28-31 * *'
  workflow_dispatch: # Allows manual trigger from Actions tab

jobs:
  run-monthly-task:
    runs-on: ubuntu-latest
    steps:
      - name: Check if today is the last day of the month
        run: |
          if [ $(date -d tomorrow +%d) -ne 01 ]; then
            echo "Today is not the last day of the month. Exiting..."
            exit 0
          fi
          echo "Today IS the last day of the month! Continuing job execution..."

      - name: Your Task
        run: |
          echo "Running your scheduled end-of-month script here..."
      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@v1
