name: Monthly Workflow

on:
  schedule:
    - cron: '0 0 28-31 * *'
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  run-monthly-task:
    runs-on: ubuntu-latest
    steps:
      - name: Check if today is the last day of the month
        id: check
        run: |
          if [ "$(date -d tomorrow +%d)" = "01" ]; then
            echo "last_day=true" >> "$GITHUB_OUTPUT"
          else
            echo "last_day=false" >> "$GITHUB_OUTPUT"
          fi
          
      - name: Sync fork from original
        if: steps.check.outputs.last_day == 'true' || github.event_name == 'workflow_dispatch'
        run: gh repo sync ${{ github.repository }} --branch master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Keepalive
        run: gh api -X PUT repos/${{ github.repository }}/actions/workflows/main.yml/enable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
